### ISSUE TITLE
use of my own dataset

### ISSUE THREAD

**Issue by fatemeh1291374** [jimmykobe/CVPR2019-MADDoG#12]
hello. Thanks for sharing your code. How can I use my own dataset for testing this model?

**Comment by rshaojimmy** [comment]
Hi,

I have shared my checkpoints of model in the drive:
https://drive.google.com/file/d/1Nsi4dxb17ZiuegMVKLPo8cr46EMjhEH8/view

You may want to test our model in your own dataset.

Thanks.
