### ISSUE TITLE
Domain generalization 

### ISSUE THREAD

**Issue by Abujami** [jimmykobe/CVPR2019-MADDoG#13]
Hey , thank you for sharing this with us. I want to try your idea on other dataset that is related to natural images (domain generalization) , this dataset is called PACS dataset each domain has seven classes and we have 4 different domains [art painting , sketch, photo, cartoon]. Do you think it is applicable ? Do you know what should I modify to make it work ? and what to take in consideration when doing that ?

Looking forward to hearing from you .

**Comment by rshaojimmy** [comment]
Hi, thanks for your interest in our work.

I think you can definitely try our work on the general DG task on PACS dataset as our method is composed of some general modules for DG except the face depth estimator. You can modify our network by just removing the face depth estimator.

Thanks.

**Comment by Abujami** [comment]
Thank you so much for your answer, I just have one question , you know that PACS dataset has 4 domains with 7 classes each. 
Can you tell me how do you think I should modify your design to fit this problem , because in your code it is all about real and fake , and you are utilizing the depth of images in the design. so should I have multiple classes the present the 7 classes? 
and how do you think that I should modify the discriminator and generator part . 

Thanks
