### ISSUE TITLE
Some questions aboout the code

### ISSUE THREAD

**Issue by taylover-pei** [jimmykobe/CVPR2019-MADDoG#2]
Congratulations, you have done a great job.

But I have two questions about the code:

1. From you code, I could only see that you just calculate the ACC (Score) for training and testing? 
How do you choose the best model to get the lowest HTER score on the target domain?

2. Can you share the code that calculate the HTER and AUC? 

Thank you very much.
Looking forward to your reply!

**Comment by rshaojimmy** [comment]
Hi, thanks for your interest in our work!

We calculate the testing scores of the target domain data based on our trained model.  Then we store these scores and use them to calculate the HTER and AUC. You can refer to [1] for the HTER calculation and AUC is a widely used metric and we just calculate them based on the common way. By the way, we have plotted the ROC curve in our paper, which can also reflect the AUC and HTER.

Thanks.

[1] Samy Bengio and Johnny Mariethoz. A statistical significance test for person authentication. In The Speaker and Language Recognition Workshop, 2004.

**Comment by taylover-pei** [comment]
I‘m glad to hear from you. But I'm still confused:

1.  In this work [Can face anti-spoofing countermeasures work in a real world scenario?](https://publications.idiap.ch/downloads/papers/2013/deFreitasPereira_ICB_2013.pdf), the HTER of the Database2 is calculate according to the threshold, which is estimated on the EER using the development set of Database1. I think there are some differences between your method and this.

2. I did not find any development set in your trainning code, so how do you find the model which performs well on the target domain? When you train the model only on the three source domains and train it until the model is converged, I think the trained model must be overfitted on the source domain and cannot perform well on the target domain. 

Thank you very much for explaining them to me. Looking forward to your reply.

Thanks.

**Comment by rshaojimmy** [comment]
Hi, following cross-testing experiments in [1,2],  the development set is not used. We train our model with data of all source domains and directly test it on the unseen target domain. Please note that our objective (domain generalization) is to let the trained model not overfitted on the source domains and be able to generalize well to the unseen target domain. 

[1] Learning Deep Models for Face Anti-Spooﬁng: Binary or Auxiliary Supervision. CVPR 2018
[2] 3D Mask Face Anti-spooﬁng with Remote Photoplethysmography. ECCV 2016

**Comment by taylover-pei** [comment]
I'm sorry to ask you one more question.

So, you just calculate the FA (False Accepatances) and FR (False Rejections) by using the threshold, which is fixed as 0.5? And then compute HTER, which is half of the FAR (FA / NI) and FRR (FR / NC)?

Thanks a lot.

**Comment by rshaojimmy** [comment]
The threshold is determined by the scores of the trained model on the source domain data rather than a fixed one. 

Thanks.

**Comment by rshaojimmy** [comment]
The threshold is not a fixed one and it is determined by the score distributions of the trained model in the different settings of domain generalization (Four settings in our paper). 

Thanks.

**Comment by taylover-pei** [comment]
Thank you very much.

I think finding the threshold is a tricky thing. And in my experiment, the threshold play a important role in the final HTER results.

**Comment by rshaojimmy** [comment]
Yes, so our paper also provides the AUC metric and ROC curve for more evaluation. In our future work, we will also provide more metrics for evaluation. Thanks for your comments.

**Comment by rshaojimmy** [comment]
If you use the same way to determine the threshold for all your compared methods in your experiments, this is also a fair comparison. And our paper also provides other evaluation metrics such as AUC and plots the ROC curve for a more comprehensive comparison. More evaluation metrics will be compared in our future work. 

Thanks.

**Comment by xuwh15** [comment]
Hello @rshaojimmy 
How did you compute your threshold exactly? I am trying to reproduce your work and I am wondering if you used any target domain data to compute the threshold?
