### ISSUE TITLE
Question about the Depth map

### ISSUE THREAD

**Issue by taylover-pei** [jimmykobe/CVPR2019-MADDoG#3]
Good job. But I have a question about the depth map.

I wonder what is the range of your depth map used in your paper? [0:1] or [0:255]?

When Iuse the PRNet to generate the depth map, I think the range of values of the depth map are [0: 255], so how should I do?

Thank you very much.

**Comment by rshaojimmy** [comment]
Hi, the range of values of the depth map is [0: 255]

Thanks.
