### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by A-bone1** [jimmykobe/CVPR2019-MADDoG#6]
Hello, how do you set the sampling ratio when processing the video, I found that the images I sampled are almost the same; there is another problem, because the image sizes of different datasets are inconsistent. What about resizing them?  Is it resize directly?  Looking forward to hearing from you

**Comment by rshaojimmy** [comment]
Hi,

1. According to the different sizes of datasets, we apply different sampling ratios to achieve data balance, such as sampling one frame from 5 or 10 frames in different datasets. 

2. We directly use the resize function to fit them into our network structure.

Thanks.

**Comment by roger-cv** [comment]
> Hello, how do you set the sampling ratio when processing the video, I found that the images I sampled are almost the same; there is another problem, because the image sizes of different datasets are inconsistent. What about resizing them? Is it resize directly? Looking forward to hearing from you
Hi, can you show me the pictures of your naming rules of these frames? (a screenshot is enough), thank you very much.
![image](https://user-images.githubusercontent.com/31872115/89905749-1f914d80-dc1d-11ea-89e8-68937991332b.png)
