### ISSUE TITLE
关于域特征提取器和域判别器的一些疑问

### ISSUE THREAD

**Issue by LiuSimon567** [jimmykobe/CVPR2019-MADDoG#7]
您好，请教一下：
1、为什么每个域需要一个判别器呢？感觉可以多个域共用一个域判别器呀，是因为要和每个域的特征提取器相对应吗？
2、感觉域特征提取器也可以多个域共用一个呀，即直接对抗训练文中的G

**Comment by rshaojimmy** [comment]
Sure, you can try this idea.
