### ISSUE TITLE
关于对比方法的ROC曲线图

### ISSUE THREAD

**Issue by roger-cv** [jimmykobe/CVPR2019-MADDoG#9]
您好，请问您的工作MADDoG和RFmetaFAS中的ROC曲线图是如何绘制的呢？如果方便的话，能分享一下对比方法以及MADDoG和RFmetaFAS的FAR & FRR数据吗？谢谢您！

**Comment by Evelyn-wst** [comment]
> 您好，请问您的工作MADDoG和RFmetaFAS中的ROC曲线图是如何绘制的呢？如果方便的话，能分享一下对比方法以及MADDoG和RFmetaFAS的FAR & FRR数据吗？谢谢您！

请问您的问题现在得到解决了吗？我也想在我的文章中绘制对比ROC曲线，请问您有对比方法以及MADDoG和RFmetaFAS的FAR & FRR数据可以分享吗

**Comment by Evelyn-wst** [comment]
> 您好，请问您的工作MADDoG和RFmetaFAS中的ROC曲线图是如何绘制的呢？如果方便的话，能分享一下对比方法以及MADDoG和RFmetaFAS的FAR & FRR数据吗？谢谢您！

请问您的问题现在得到解决了吗？我也想在我的文章中绘制对比ROC曲线，请问您有对比方法以及MADDoG和RFmetaFAS的FAR & FRR数据可以分享吗

**Comment by rshaojimmy** [comment]
Hi I have shared my checkpoints of model in the drive:
https://drive.google.com/file/d/1Nsi4dxb17ZiuegMVKLPo8cr46EMjhEH8/view

You may want to plot ROC curve based on the prediction scores.

Thanks.
